src/app/api/test/route.ts
src/app/interview/feedback/loading.tsx
src/app/interview/feedback/page.tsx
src/app/interview/ongoing/page.tsx
src/components/header.tsx
src/data/questions.ts
src/data/test.ts
src/styles/globals.css
src/types/types.d.ts
src/utils/format.ts

🌱 작업한 브랜치
- feature/DV-66-add-text-interview-ongoing
- 면접 진행 UI 추가
- 답변 타이머 추가 (3분)
- 피드백 페이지 로딩 추가
- loading.tsx 파일은 page.tsx가 Server Component이고 api 비동기 요청이 만료되지 않았을 경우 자동으로 보여지는 페이지입니다.

DV-66 면접 진행 UI 및 로직 추가

---

src/styles/globals.css

🌱 작업한 브랜치
- feature/DV-134-delete-dark-mode-style
* dark 모드일 때 배경색을 검정으로 설정하는 스타일을 제거했습니다. dark 모드는 나중에 생각하면 좋을 것 같습니다.

DV-134 feat: dark 모드일 때 배경색 입히는 스타일 제거

---

package.json
src/app/interview/feedback/page.tsx

🌱 작업한 브랜치
- hotfix/DV-139-port-number-update
- npm start 시 포트번호를 3000에서 8080으로 변경하였습니다.

[DV-139] npm start 포트번호 변경

---

package-lock.json
package.json
src/app/page.tsx
src/components/footer.tsx

🌱 작업한 브랜치
- feature/DV-137-landing-page
- footer에 ⓒ 2024 Richard Stallman Corp. 라는 내용을 추가하였습니다.
- 랜딩페이지에 서비스명과 캐치프레이즈를 추가하였습니다.
- 랜딩페이지에 애니메이션 효과를 주었습니다.
- 면접과 관련된 깔끔한 랜딩페이지 이미지를 찾지 못해 애니메이션 효과로 랜딩페이지를 바꿔보았습니다. 시간되시면 브랜치 들어가서 확인해주시면 더 확실하게 보실 수 있을 것 같습니다.
- 시작하기 버튼 색깔이 현재 blue-600으로 되어있는데 primary 색상으로 해보니 현재 배경색과는 어울리지 않는 것 같아 다시 blue로 변경하였습니다. 저희 서비스 기본색이랑 맞지 않는 부분으로 판단되면 primary 색상으로 변경하도록 하겠습니다.

[DV-137] 랜딩페이지 UI 구현

---

package.json

🌱 작업한 브랜치
- feature/DV-146-package-json-hotfix
"node_modules/next/dist/bin/next start -p 8080" 내용 추가

[DV-146] hotfix: package.json 내용 추가

---

src/app/mypage/coupon/page.tsx
src/app/mypage/edit/page.tsx
src/app/mypage/layout.tsx
src/app/mypage/payment-history/page.tsx
src/app/mypage/voucher/page.tsx

🌱 작업한 브랜치
- feature/DV-164-payment
- 쿠폰함 UI 구현
- 이용권 UI 구현
- 결제내역 UI 구현
- 이용권 결제창 모달 구현
- 쿠폰함 UI
- 이용권 UI
- 이용권 결제모달
<매수 추가>
- 결제내역 UI

[DV-164] 결제로직 관련 UI 구현

---

src/app/mypage/voucher/page.tsx

🌱 작업한 브랜치
- hotfix/DV-194-payment-error
- 쿠폰으로 이용권 결제가 안되던 문제를 해결하였습니다.

[DV-194] 쿠폰으로 이용권 결제 안되던 문제 해결

---

public/firebase-messaging-sw.js
src/utils/firebaseConfig.ts

🌱 작업한 브랜치
- DV-193-fe-add-google-analytics-and-update-fcm-config
- firebase analytics 적용 및 firebase 관련 정보 공식 계정으로 수정
- 따로 전송해드린 .env 추가하시면 됩니다!

feat : google analytics 적용 및 정보 수정

---

src/app/(user)/auth/page.tsx
src/app/(user)/signup/page.tsx
src/app/interview/feedback/[interviewId]/page.tsx
src/app/interview/ongoing/[interviewId]/page.tsx
src/app/interview/ongoing/prepare/page.tsx
src/app/interview/page.tsx
src/app/mypage/coupon/page.tsx
src/app/mypage/edit/page.tsx
src/app/mypage/feedback/[interviewId]/page.tsx
src/app/mypage/feedback/page.tsx
src/app/mypage/layout.tsx
src/app/mypage/payment-history/page.tsx
src/app/mypage/voucher/page.tsx
src/components/interview/interview-feedback-detail.tsx
src/components/interview/setup-funnel.tsx
src/components/interview/step/check-info-step.tsx
src/components/interview/step/method-step.tsx
src/components/payment-modal.tsx
src/stores/useQuestionRequest.ts
src/types/coupon.d.ts
src/types/interview.d.ts
src/types/types.d.ts
src/types/user.d.ts

🌱 작업한 브랜치
- DV-198-fe-text-interview-api-connection
- 텍스트 면접 흐름 정리 / api 연결
- interface 파일로 모음
- 너무 많이 건드리게 된 것 같긴 한데.. 생각한 방향이 아니라면 말씀해주세요!
- 평가 저렇게 보이는 건 중간에 답변평가들을 파이썬에서 받아와야하는데 프론트 연결 테스트로 파이썬에서 보내주는 요청은 postman으로 대충 대체해서 그렇습니다..!
|기능|스크린샷|
|:--:|:--:|
|실전 채팅 선택 시 UI|<img width="712" alt="image" src="https://github.com/user-attachments/assets/1f410304-30e2-494e-92cb-02e3ea82070b">|
|모의 채팅 선택 시 UI|<img width="828" alt="image" src="https://github.com/user-attachments/assets/5a72f07c-fb47-4430-8f9c-f46f6ec5b0b4">|
|보유 이용권 부족 시 이용권 결제 버튼 활성화 / 면접 시작 버튼 비활성화 | <img width="831" alt="image" src="https://github.com/user-attachments/assets/ba965ab2-58e9-41c8-988b-da87bafccf2a">|
|질문 개수 선택 전 선택 안내 문구 및 면접 시작 버튼 비활성화|<img width="910" alt="image" …

Dv 198 fe text interview api connection

---

src/app/interview/ongoing/page.tsx

🌱 작업한 브랜치
- feature/DV-201-voice-file-s3-upload
- 녹음 시작 버튼을 누르고 음성면접을 진행한 뒤 다음 질문으로 넘어가면 음성파일이 webm 파일로 S3로 올라가도록 하였습니다.
- 이어서 mp3 파일로 올라가도록 작업할 예정입니다.

[DV-201] S3에 음성파일 업로드 되도록 하기

---

src/app/interview/ongoing/prepare/page.tsx

🌱 작업한 브랜치
- hotfix/DV-205-chat-no-mic-check
- 채팅면접시에는 마이크허용창이 뜨지 않도록 수정하였습니다.

[DV-205] 채팅면접에서는 마이크 허용창 안뜨도록 하기

---

src/components/user-form.tsx

🌱 작업한 브랜치
- DV-204-fe-validate-nickname
- 중복 검사를 안 했을 경우 회원가입 불가능
- username이 중복일 경우 회원가입 불가능

[DV-204] username 중복 검사를 안했거나 중복일 경우에는 회원가입 못하게 하기

---

src/app/page.tsx
src/components/header.tsx

🌱 작업한 브랜치
- DV-206-fe-login-checking
- [DV-206] 로그인이 안되었을 경우 로그인 페이지로 redirect
[DV-206]: https://richardstallman.atlassian.net/browse/DV-206?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DV-206] 로그인이 안되었을 경우 로그인 페이지로 redirect

---

package.json
src/app/interview/ongoing/[interviewId]/page.tsx
src/app/interview/ongoing/page.tsx
src/app/interview/ongoing/prepare/page.tsx
src/components/interview/step/check-info-step.tsx
src/types/mic-recorder-to-mp3.d.ts

DV-202-fe-user-update-and-payment-voice-implement
- mp3 파일 s3에 업로드
- 이용권 음성까지 체크

Dv 202 fe user update and payment voice implement

---

package-lock.json
src/app/interview/ongoing/prepare/page.tsx
src/app/interview/page.tsx
src/components/interview/step/type-step.tsx
src/components/mic-test.tsx
src/components/user-form.tsx

🌱 작업한 브랜치
- hotfix/DV-211-front-issue
- 모의 인성 면접 버튼 비활성화
- 음성 면접 시 마이크테스트 이후 질문생성 로딩 창 띄우기

[DV-211] 프론트 이슈 처리 및 음성로딩 페이지 리팩토링

---

src/components/user-form.tsx

🌱 작업한 브랜치
- feature/DV-217-mypage-issue
- 이름, 유저네임은 20글자 이내, 닉네임은 15글자 이내로 제한하기
- 생년월일 오늘날짜 이후는 클릭 안되도록 하기

[DV-217] 마이페이지 자잘한 이슈 해결

---

package-lock.json
package.json
src/app/interview/ongoing/[interviewId]/page.tsx
src/components/RecordingIndicator.tsx
src/types/interview.d.ts

🌱 작업한 브랜치
- feature/DV-231-TTS-voice-interview
- 음성면접 진행 시 TTS 된 audio를 화면 진입 후 2초 뒤 재생하기
- 질문 재생이 종료되면 자동으로 녹음 시작하기
- 질문 재생 중일때는 다음(제출) 버튼 비활성화
- 면접 진행 중 새로고침하려고 하면 경고창 띄워주기
- 녹음 파일 올라갈 때 나오는 토스트 제거
- 녹음 중일때 디자인 추가
- TTS 오디오가 재생되는 부분은 브랜치를 통해 직접 확인해주시길 바랍니다!

[DV-231] 음성 면접 진행 과정 구현

---

src/components/user-form.tsx

🌱 작업한 브랜치
- feature/DV-235-mypage-issue
- 이름은 10자, 유저네임은 15자로 글자수를 변경
- 이름은 영어와 한국어만 입력되도록 변경

[DV-235] 마이페이지 이름, 유저네임 관련 로직 수정

---

src/app/mypage/feedback/page.tsx
src/components/EvaluationCriteriaList.tsx
src/components/interview/interview-feedback-detail.tsx

🌱 작업한 브랜치
- feature/DV-241-feedback-refactoring
- 음성면접 시 전반적인 평가에서 음성관련 내용은 아래에 모으기
- 면접평가확인 페이지에서 제목 구조 변경

[DV-241] 피드백 관련 수정

---

next.config.ts

feat : s3 주소 동적 할당

---

src/app/community/page.tsx
src/components/interview/interview-feedback-detail.tsx

🌱 작업한 브랜치
- feature/DV-260-personal-snsimg-issue
- 인성면접에서 전반적인 평가 라벨링 잘못되고 있던 부분 수정
- SNS 글작설할때 프로필 이미지 안 뜨던 부분 수정

[DV-260] 인성면접 평가, SNS 프로필 이미지 오류 해결
